### ISSUE TITLE
The question about Q function in code.

### ISSUE THREAD

**Issue by zcfinal** [lunanbit/FedUL#1]
Hi. Thanks for your excellent work and codes.
I have a question about Q function in code. It seems that QfunctionMulticlass doesn't use the test class prior. It only uses Pi and priors_corr. There are some differences between the code and Theorem 1.
Could you please explain that?

**Comment by Kyfafyd** [comment]
Thanks for your interest!
In our benchmark experiments, the test data is uniformly distributed in regard of class priors.
In Theorem 1, we give the general formula with the test class priors.

For detailed experimental settings, you can check the `Setup` on Page 7 in our paper.

**Comment by zcfinal** [comment]
I see. Thanks!
